### ISSUE TITLE
Government Documents surrounding UFOs

### ISSUE THREAD

**Issue by mjo43** [haggis78/Nexus#11]
Countries all over the world have referenced UFOs in military reports dating back to WWII. "Foo Fighters" was a term used to describe these unknown objects in the sky. Since then, documents released by the U.S., Russia, Germany, and many more declassified documents referencing the craft in the sky as well as some incidents of crashes.
       Recently, videos released by the pentagon, <https://www.fox10phoenix.com/news/not-made-on-this-earth-top-secret-pentagon-ufo-task-force-reportedly-expected-to-reveal-some-findings>, have brought more attention to the subject, which could make an interesting topic for a project. Depending on how many documents we can find and the information they possess, the focus of the project could be a specific country or phenomenon. The XML could allow quick navigation between documents of similar accounts and key terms.
       Transcribing these documents would be the bulk of the work in producing a single website of official information. Any document lacking credibility would not be used in the project. The goal is to not make any stretches to try to fit the UFO narrative. This isn't Ancient Aliens. Project Blue Book could be a great resource for finding plenty of documents.

"From 1947 to 1969, a total of 12, 618 sightings were reported to Project BLUE BOOK. Of these 701 remain "Unidentified." The project was headquartered at Wright-Patterson Air Force Base, whose personnel no longer receive, document or investigate UFO reports." 
- https://www.archives.gov/research/military/air-force/ufos

**Comment by haggis78** [comment]
That's a very cool idea. How much research have you done into finding out what material is freely available? That's crucial. In theory you could try to take a flying trip to The National Archives itself to get copies or photographs of documents, but at the moment it's closed due to COVID-19. So what's already in print or on the web; what's its copyright status; and do you trust its accuracy?
Here's one document I found, but of course you would need a lot more: 
https://www.cia.gov/library/readingroom/docs/CIA-RDP81R00560R000100040013-4.pdf

**Comment by khope168** [comment]
I really like the idea!

**Comment by mld137** [comment]
This seems like an interesting topic, I like the idea of pulling together different types of sources (like documents, pictures, etc.) and making a space to put everything into one cohesive site.

**Comment by JakeCode121** [comment]
Something like this seem very doable.

**Comment by haggis78** [comment]
@mjo43 This was a cool idea.
