### ISSUE TITLE
The Hamilton Project

### ISSUE THREAD

**Issue by mld137** [haggis78/Nexus#15]
Hamilton is the Broadway musical depicting the story of Alexander Hamilton during his time as a founding father. With no dialogue the show emphasizes on characters and lyrics to tell the story (the founding fathers rap and if you have not seen Hamilton I recommend giving Yorktown a listen https://www.youtube.com/watch?v=WQt1RRW_xv0 ). The show focuses mainly on Alexander and his story, but also emphasizes the important figures who helped him make his legacy.Hamilton eventually lead a battalion of men to win the revolutionary war, and establish the US national banking system through these he faced many obstacles during his life (including the decision to publish an affair he had while his wife was away for the summer). Hamilton was dedicated to making a name for himself and his goal was accomplished but at many costs. The same is true for the other historical figures in the show, Aaron Burr for example kills Alexander in a duel after the election of 1800, but after watching the show, you can almost understand why Burr feels it is necessary. So while Hamilton is more captivating than a history book, does that pose the threat of leaving out important pieces of history? The Hamilton project would investigate the historical accuracy of Hamilton’s story line and to look at how accurately the characters are portrayed. This could be done by looking at each main character, giving background information on them, and analyzing how their character is portrayed in the show. For example, George Washington was a slave owner, however in the show it is only mentioned that he is from the south, never that he himself had slaves. Secondly, we can look at lyrics within the show pieces and reference letters or other documents to map out how accurately Hamilton follows history.

**Comment by haggis78** [comment]
That's a cool idea -- though something similar was done before in this class:

http://hamilton.newtfire.org/

See especially http://hamilton.newtfire.org/vis_FactFiction.html 

Now, that's not a kibosh on your project. That was in the Coding and Data Visualization class, so the emphasis was somewhat different. It shows that the source material is available. But you would have to be confident that you could develop something significantly new with it. For example, instead of just classifying things as fact or fiction, you could hunt down the actual primary historical sources regarding each claim and encode them. If this project runs, I'll liase with Dr. Beshero-Bondar about the parameters for re-use of code.

**Comment by ebeshero** [comment]
@haggis78 @mld137 Hi there! You can ping me directly on GitHub, you know! :-) I'm excited to see more interest in Hamilton! The site at https://hamilton.newtfire.org was built over two semesters, actually, and started in the Coding and Digital Archives as markup over the open source texts of the musical score. The question is, what could you do that builds on that project or relates to it?

**Comment by haggis78** [comment]
@mld137 Well, you didn't throw away your shot, but it didn't work out. I was secretly rooting for this and had lots of ideas buzzing around my head. I particularly liked you idea of looking for important things that were ignored or glossed over -- that's good historical thinking right there.
